### ISSUE TITLE
[UPDATE] Quotations endpoint

### ISSUE THREAD

**Issue by hiro-riveros** [kattatzu/shipIt#3]
Hi,

At the beginning of 2018, Shipit launched, a new version of quotations end-point. This end-point uses version 3 of our public API.

It includes a new response object and also includes a new request object.

here's the documentation: [https://developers.shipit.cl/reference#consultar-precio-version-estable](https://developers.shipit.cl/reference#consultar-precio-version-estable)

Best.

**Comment by HaneulChile** [comment]
Hi hiro-riveros
I have the same problem but I dont know how to solve it. Can you help me please? I know now that I need to use the v3 in order to ask for a price. But when I change in the function the endpoint I receive a error 404 not found.
Thanks if you can help me
